import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "payment-api/crowdsplit-api",
    },
    {
      type: "category",
      label: "Auth",
      link: {
        type: "doc",
        id: "payment-api/auth",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/signup",
          label: "User sign up",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/verify-signup-email",
          label: "Verify email address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/resend-verification-email",
          label: "Resend verification email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/signin",
          label: "Sign in",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/refresh-token",
          label: "Refresh access token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/validate-token",
          label: "Validate access token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/reset-password",
          label: "Request password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/verify-reset-password-token",
          label: "Verify password reset token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-password",
          label: "Update password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Merchants",
      link: {
        type: "doc",
        id: "payment-api/merchants",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-merchant",
          label: "Create a merchant account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/create-merchant-key",
          label: "Create merchant API keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/grant-merchant-token",
          label: "Grant merchant token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/refresh-merchant-token",
          label: "Refresh merchant token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/calculate-transfer-date",
          label: "Calculate transfer date",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Customers",
      link: {
        type: "doc",
        id: "payment-api/customers",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-customer",
          label: "Create a customer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/list-customers",
          label: "List all customers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-customer",
          label: "Get customer details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-customer",
          label: "Update a customer",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payment-api/sync-customer",
          label: "Sync customer data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-customer-balances",
          label: "Get customer balances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/upload-customer-files",
          label: "Upload customer files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-customer-files",
          label: "Get customer files",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Payment Methods",
      link: {
        type: "doc",
        id: "payment-api/payment-methods",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-payment-method",
          label: "Add a payment method",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/list-payment-methods",
          label: "List payment methods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-payment-method",
          label: "Get payment method details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-payment-method",
          label: "Update a payment method",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payment-api/delete-payment-method",
          label: "Delete a payment method",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Provider Registration",
      link: {
        type: "doc",
        id: "payment-api/provider-registration",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/populate-kyc-data",
          label: "Submit platform registration data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-kyc-schema",
          label: "Get KYC schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/submit-kyc",
          label: "Submit provider registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-kyc-status",
          label: "Check provider registration status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Payments",
      link: {
        type: "doc",
        id: "payment-api/payments",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-payment",
          label: "Create a payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/confirm-payment",
          label: "Confirm a payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/capture-payment",
          label: "Capture a payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/cancel-payment",
          label: "Cancel a payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/refund-payment",
          label: "Refund a payment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Payouts",
      link: {
        type: "doc",
        id: "payment-api/payouts",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-payout",
          label: "Create an outbound payment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Transfers",
      link: {
        type: "doc",
        id: "payment-api/transfers",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-transfer",
          label: "Create a transfer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/send-transfer-webhook",
          label: "Send transfer webhook (dev)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Buy / Sell",
      link: {
        type: "doc",
        id: "payment-api/buy-sell",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/create-buy",
          label: "Create a buy transaction",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Wallets",
      link: {
        type: "doc",
        id: "payment-api/wallets",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/get-wallet-balance",
          label: "Get trading wallet balance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/create-wallet-buy",
          label: "Create a wallet buy trade",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Transactions",
      link: {
        type: "doc",
        id: "payment-api/transactions",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/list-transactions",
          label: "List transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-transaction",
          label: "Get transaction details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/settle-transaction",
          label: "Settle a transaction",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Disputes",
      link: {
        type: "doc",
        id: "payment-api/disputes",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/list-disputes",
          label: "List disputes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-dispute-evidence",
          label: "Upload dispute evidence",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payment-api/submit-dispute",
          label: "Submit dispute for review",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payment-api/close-dispute",
          label: "Close a dispute",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Subscriptions",
      link: {
        type: "doc",
        id: "payment-api/subscriptions",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/list-plans",
          label: "List subscription plans",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/create-plan",
          label: "Create a subscription plan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-plan",
          label: "Get plan details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-plan",
          label: "Update a plan",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payment-api/delete-plan",
          label: "Delete a plan",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "payment-api/publish-plan",
          label: "Publish a plan",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payment-api/subscribe",
          label: "Subscribe to a plan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/cancel-subscription",
          label: "Cancel a subscription",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payment-api/list-subscriptions",
          label: "List subscriptions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-subscription",
          label: "Get subscription details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/initiate-subscription-payment",
          label: "Initiate subscription payment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tax",
      link: {
        type: "doc",
        id: "payment-api/tax",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/calculate-taxes",
          label: "Calculate taxes",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      link: {
        type: "doc",
        id: "payment-api/files",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/upload-files",
          label: "Upload files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/list-files",
          label: "List files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-file",
          label: "Get file details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/delete-file",
          label: "Delete a file",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Generic",
      link: {
        type: "doc",
        id: "payment-api/generic",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/generic-provider-proxy",
          label: "Generic provider proxy call",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "System",
      link: {
        type: "doc",
        id: "payment-api/system",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/health-check",
          label: "Health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/list-countries",
          label: "List countries",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      link: {
        type: "doc",
        id: "payment-api/webhooks",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/list-webhooks",
          label: "List webhooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/register-webhook",
          label: "Register a webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payment-api/get-webhook",
          label: "Get webhook details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/update-webhook",
          label: "Update a webhook",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payment-api/delete-webhook",
          label: "Delete a webhook",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "payment-api/toggle-webhook-status",
          label: "Toggle webhook active status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payment-api/list-webhook-notifications",
          label: "List webhook notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payment-api/get-webhook-notification",
          label: "Get webhook notification details",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Webhook Events",
      link: {
        type: "doc",
        id: "payment-api/webhook-events",
      },
      items: [
        {
          type: "doc",
          id: "payment-api/webhook-payment-awaiting-confirmation",
          label: "Payment awaiting confirmation",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-cancelled",
          label: "Payment cancelled",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-captured",
          label: "Payment captured",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-failed",
          label: "Payment failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-installment-failed",
          label: "Installment payment failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-installment-succeeded",
          label: "Installment payment succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-processing",
          label: "Payment is processing",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-refunded",
          label: "Payment refunded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-succeeded",
          label: "Payment succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-updated",
          label: "Payment updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-transaction-sc-updated",
          label: "Transaction settlement/checkpoint updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-transaction-updated",
          label: "Transaction updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-refund-created",
          label: "Refund created",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-refund-failed",
          label: "Refund failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-refund-updated",
          label: "Refund updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-standalone-refund-failed",
          label: "Refund failed (standalone)",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-standalone-refund-succeeded",
          label: "Refund succeeded (standalone)",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-dispute-closed",
          label: "Dispute closed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-dispute-funds-reinstated",
          label: "Dispute funds reinstated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-dispute-funds-withdrawn",
          label: "Dispute funds withdrawn",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-dispute-updated",
          label: "Dispute updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-dispute-created",
          label: "Payment disputed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-action-required",
          label: "Customer action required",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-created",
          label: "Customer created",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-processing",
          label: "Customer processing",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-rejected",
          label: "Customer rejected",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-updated",
          label: "Customer updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-verified",
          label: "Customer verified",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-kyc-action-required",
          label: "KYC action required",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-kyc-approved",
          label: "KYC approved",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-kyc-rejected",
          label: "KYC rejected",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-action-required",
          label: "Provider registration action required",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-approved",
          label: "Provider registration approved",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-awaiting-confirmation",
          label: "Provider registration awaiting confirmation",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-documents-uploaded",
          label: "Provider registration documents uploaded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-processing",
          label: "Provider registration processing",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-rejected",
          label: "Provider registration rejected",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-restricted",
          label: "Provider registration restricted",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-submitted",
          label: "Provider registration submitted",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-updated",
          label: "Provider registration updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-prov-reg-verification-expired",
          label: "Provider registration verification expired",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-sync-failed",
          label: "Customer sync failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-sync-started",
          label: "Customer sync started",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-customer-sync-succeeded",
          label: "Customer sync succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-method-approved",
          label: "Payment method approved",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-method-created",
          label: "Payment method created",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-method-rejected",
          label: "Payment method rejected",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-method-updated",
          label: "Payment method updated",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payment-method-verified",
          label: "Payment method verified",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-transfer-failed",
          label: "Transfer failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-transfer-succeeded",
          label: "Transfer succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-payout-succeeded",
          label: "Payout succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-buy-awaiting-confirmation",
          label: "Buy awaiting confirmation",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-buy-completed",
          label: "Buy completed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-buy-succeeded",
          label: "Buy succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-sell-failed",
          label: "Sell failed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-sell-succeeded",
          label: "Sell succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-external-deposit-awaiting-confirmation",
          label: "External deposit awaiting confirmation",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-external-deposit-completed",
          label: "External deposit completed",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-external-deposit-received",
          label: "External deposit received",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-external-deposit-succeeded",
          label: "External deposit succeeded",
          className: "api-method event",
        },
        {
          type: "doc",
          id: "payment-api/webhook-external-virtual-account-funded",
          label: "External virtual account funded",
          className: "api-method event",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
